#server:
#  address: 0.0.0.0
#  port: ${PORT:8080}

server:
  port: 1292

management:
  server:
    port: 1293

#spring:
#  datasource:
#    url: jdbc:mysql://google/expense_tracker?cloudSqlInstance=totemic-fact-386917:europe-central2:expense-tracker&socketFactory=com.google.cloud.sql.mysql.SocketFactory
#    username: root
#    password: Password123!
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  flyway:
#    schemas:
#        - expense_tracker

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/expense_tracker
    username: root
    password: manager
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    schemas:
      - expense_tracker